### ISSUE TITLE
Needs a 128x128px icon

### ISSUE THREAD

**Issue by nedrichards** [flathub/com.github.ojubaorg.Othman#1]
For some reason, this isn't getting a 128x128px icon on the [apps page](https://beta.flathub.org/apps), which is strange, since there's one in the upstream source.

**Comment by muayyad-alsadi** [comment]
file it upstream

**Comment by muayyad-alsadi** [comment]
here, it's

https://github.com/ojuba-org/othman/issues/14

**Comment by nedrichards** [comment]
Thanks!

**Comment by muayyad-alsadi** [comment]
if you need a vector icon here it's

https://github.com/ojuba-org/othman/blob/master/othman-data/quran-kareem.svg
